// Generated by scripts/build-templates.mjs — do not edit.
//
// Source: proposal-templates/. Add or change a template there and run
// `npm run deploy:fn concept-note`, which regenerates this file before it
// deploys. Editing it here would be overwritten by the next deploy, and would
// put the running structure out of step with the folder anyone reads to see it.

export interface UploadedTemplate {
  /** The file's own name, shown in the console so a draft is traceable to it. */
  name: string
  /** Its readable text: Markdown headings, or a Word file's headings rebuilt. */
  body: string
}

export const UPLOADED_TEMPLATES: UploadedTemplate[] = []
