/**
 * Flattens supabase/migrations into supabase/my_database.sql.
 *
 * The migrations are the source of truth — a history of changes, each carrying
 * the reasoning for its own. This is the other view: what the schema should
 * look like right now, in one file, for pasting into the Supabase SQL Editor.
 *
 * WHY THIS IS A SCRIPT AND NOT A ONE-OFF CONCATENATION. Ten of the migrations
 * write data as well as defining structure, and the two cannot be told apart by
 * eye at speed. An `insert` at the top level of 0017 seeds claim rows and must
 * go; an `insert` four lines into 0013 is the body of handle_new_user() and must
 * stay. Deleting both — which is what a grep for "insert into" does — silently
 * breaks five functions while looking like it worked. The exclusions below are
 * therefore named by file and line, verified by hand, and re-applied the same
 * way every time.
 *
 * The output is safe to run against a populated database: what survives is
 * tables, indexes, functions, triggers, policies and grants, all written
 * `if not exists` or `create or replace`.
 *
 * Run after changing any migration:
 *   npm run schema:build
 */

import { readFileSync, writeFileSync, readdirSync } from 'node:fs'
import { join } from 'node:path'

const DIR = 'supabase/migrations'
const OUT = 'supabase/my_database.sql'

/**
 * Migrations that are data end to end — no DDL in them at all.
 *
 * Named rather than detected. A file with no `create` in it is *probably* a
 * data migration, but "probably" is not a basis for dropping something from a
 * schema, and the reason belongs on the record where the next person can
 * disagree with it.
 */
const SKIP = {
  '0006_strip_source_prefix.sql': 'rewrites existing rfps.source values',
  '0027_remove_work_we_do_not_do.sql': 'deletes rfps rows that no longer qualify',
}

/**
 * Top-level data statements inside otherwise-structural migrations, as
 * 1-based inclusive line ranges.
 *
 * Nothing inside a function body appears here. Those inserts and deletes are
 * part of the definition being created, not writes performed by the migration:
 * handle_new_user, seed_member_rfps, consume_api_quota, record_change and
 * empty_expired_proposal_archive all contain one and all must keep it. The two
 * `insert into storage.buckets` statements stay for the same reason — they
 * create a bucket, they do not write anyone's data.
 *
 * Line ranges break if a migration is edited above them. `verify` below is what
 * catches that.
 */
const STRIP = {
  '0013_roles.sql': [[115, 119]], // backfill profiles from auth.users
  '0017_rfp_claims.sql': [[60, 70]], // seed claims from in-pipeline rfps
  '0026_capability_statement_services.sql': [[1, 119]], // bulk service_areas rewrites
}

const files = readdirSync(DIR).filter((f) => f.endsWith('.sql')).sort()
const out = []
const omitted = []

for (const file of files) {
  if (SKIP[file]) {
    omitted.push(`${file} — entire file: ${SKIP[file]}`)
    continue
  }
  let lines = readFileSync(join(DIR, file), 'utf8').split(/\r?\n/)
  for (const [from, to] of STRIP[file] ?? []) {
    for (let i = from - 1; i < to && i < lines.length; i += 1) lines[i] = null
    omitted.push(`${file} — lines ${from}-${to}`)
  }
  lines = lines.filter((line) => line !== null)
  const rule = '='.repeat(75)
  out.push(`-- ${rule}\n-- ${file}\n-- ${rule}\n`)
  out.push(lines.join('\n').trim(), '\n')
}

const rule = '='.repeat(75)
const header = `-- ${rule}
-- MY DATABASE — complete schema, Pipeline Console
--
-- GENERATED by scripts/build-schema.mjs. Do not edit by hand: change the
-- migration under supabase/migrations and re-run \`npm run schema:build\`.
--
-- Every migration in order, with data statements removed. Run the whole file in
-- ONE Supabase SQL Editor tab. Safe against a live database: what remains is
-- tables, indexes, functions, triggers, policies and grants, all written
-- \`if not exists\` or \`create or replace\`.
--
-- WHAT WAS LEFT OUT, and why. These rewrite or delete rows rather than define
-- structure, so running them against a populated database would duplicate or
-- destroy real records:
${omitted.map((entry) => `--   ${entry}`).join('\n')}
--
-- Statements that only look like data are KEPT: inserts inside function bodies
-- (handle_new_user, seed_member_rfps, consume_api_quota, record_change,
-- empty_expired_proposal_archive) are part of those definitions, and the two
-- storage.buckets inserts create buckets rather than write user data.
-- ${rule}

`

const sql = header + out.join('\n')
writeFileSync(OUT, sql)

/**
 * Sanity checks on the output.
 *
 * The line ranges above are the fragile part — edit a migration above one and
 * it silently strips the wrong lines. These catch the two ways that goes wrong:
 * a data statement surviving, or a function body losing its closing delimiter.
 */
const problems = []
const strays = sql
  .split('\n')
  .map((line, index) => [line, index + 1])
  .filter(([line]) => /^(insert into|update|delete from) public\./.test(line))
if (strays.length) {
  problems.push(`data statements survived at lines: ${strays.map(([, n]) => n).join(', ')}`)
}
const dollars = (sql.match(/\$\$/g) ?? []).length
if (dollars % 2 !== 0) {
  problems.push(`unbalanced $$ delimiters (${dollars}) — a function body was cut`)
}
const tables = (sql.match(/create table if not exists public\./g) ?? []).length

console.log(`${OUT}: ${sql.split('\n').length} lines, ${tables} tables`)
console.log(`included ${files.length - Object.keys(SKIP).length} of ${files.length} migrations`)
for (const entry of omitted) console.log(`  omitted: ${entry}`)
if (problems.length) {
  for (const problem of problems) console.error(`  PROBLEM: ${problem}`)
  process.exit(1)
}
console.log('checks passed')
